### PR TITLE
Add cpanfile

### PR DESCRIPTION
**Pull request by 1nickt**
Add a `cpanfile` to manage dependencies. 

```
[594] ► perlbrew use 5.26.1t

[595] ► perl -Mthreads -E 1

[596] ► cpanfile-dump cpanfile
Time::HiRes
Tk
WWW::Mechanize
XML::LibXML

[597] ► perlbrew use 5.26.1c

[598] ► perl -Mthreads -E 1
This Perl not built to support threads
Compilation failed in require.
BEGIN failed--compilation aborted.

[599] ► cpanfile-dump cpanfile
MCE::Hobo
MCE::Shared
Time::HiRes
Tk
WWW::Mechanize
XML::LibXML
```

### CODE REVIEW

**Comment by 1nickt** [comment]
@choroba I wanted to use an eval to test whether the perl is threaded, as I am not sure that the string has always been or always will be the same, but I could not get the check to work right when under Perlbrew:
```
[685] ► perl -Mthreads -E 1

[686] ► cat cpanfile 
use feature 'say';
say $];
say eval { require 'threads'; 1 } ? 1 : 0;
__END__

[687] ► cpanfile-dump cpanfile 
5.022001
0

[688] ► which cpanfile-dump 
/home/nick/perl5/perlbrew/perls/perl-5.26.1t/bin/cpanfile-dump

[689] ► /home/nick/perl5/perlbrew/perls/perl-5.26.1t/bin/cpanfile-dump cpanfile 
5.026001
0

# WTF?
```

**Comment by marioroy** [comment]
@1nickt, another way.

```perl
my $has_threads;

BEGIN {
    eval 'use threads';
    $has_threads = $INC{'threads.pm'} ? 1 : 0;
}

```

**Comment by 1nickt** [comment]
Thanks @marioroy ! 

( I had an error in my eval syntax too )

**Comment by choroba** [comment]
To check for threads, you can use

```perl
use Config;
if ($Config{usethreads}) ...
```

**Pull request closed without merging**
