### PR TITLE
Allow for use with perlbrew etc

### PR DESCRIPTION
**Pull request by yewtc**
I was assigned this module as part of the "pull request club" and when trying to run the code up in a perlbrew environment - it failed because of the shebang line. So this change is merely to switch to #/usr/bin/env  perl instead. This is my first pull request through the PRC, and almost my first PR, so please be gentle with me.

### CODE REVIEW

**Comment by choroba** [comment]
I'm not a big fan of env in shebang lines. See for example [Why is it better to use “#!/usr/bin/env NAME” instead of “#!/path/to/NAME” as my shebang?](https://unix.stackexchange.com/q/29608/13792) I'd just run the scripts as `perl pm-cb-g` under perlbrew.

The PR is OK formally, but I'm hesitating to accept it. Are you sure you can't come up with something else in the remaining three weeks? :crossed_fingers:

**Comment by yewtc** [comment]
Ok - just missed Jan. But Here is a fix to issue #44. 
So the messages are sort of xml, but hand crafted, so a formal xml parsing solution propbably won't go well. So...  I went for a regex solution and it seems to work. There might be some corner cases that for which it won't work. I've had it running locally for a while it seems to behave.

**Comment by choroba** [comment]
Thanks, merged as #46

**Comment by choroba** [comment]
Using regexes is definitely the way to go here. What we're processing is user input which could be broken in any way imaginable.

**Pull request closed without merging**
